# Generated by Django 6.0.7 on 2026-08-22 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_certificate_unique_user_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
